### ISSUE TITLE
Unsatisfiable dependency

### ISSUE THREAD

**Issue by colehaus** [csicar/purescript-graphviz#3]
Sorry, I had guessed that you'd be bumping both this and `purescript-dotlang` to `2.0.0` so the `bower.json` here specifies that as the required version of `purescript-dotlang`. I'm not sure which fix you prefer: Changing the release tags or changing the dependency here?

**Comment by csicar** [comment]
oh, I see. I prefer changing the `bower.json` version, if you don't mind

**Comment by colehaus** [comment]
Thanks! Any chance of getting them up on bower/pursuit too?

**Comment by csicar** [comment]
Give me a second ..

**Comment by csicar** [comment]
https://pursuit.purescript.org/packages/purescript-dotlang/1.2.0
https://pursuit.purescript.org/packages/purescript-graphviz/1.1.1 (! this version is dumped over the previous!)

**Comment by colehaus** [comment]
Thanks!
